// ============================================================================
// OpsBriefCard
// Signals "your desk publishes a weekly ops brief and one lands Monday
// morning." The brief itself is generated by the morningBriefCron on
// the operator side; this card gives the client visibility that it's on
// the calendar. Universal (all client profiles see this), because
// operations continuity is a supply-chain-manager service regardless of
// whether the client ships cross-border.
// ============================================================================

import { useEffect, useState } from "react";
import { FileText, Calendar, Loader2 } from "lucide-react";
import { api, ApiError } from "../config/api";

interface Summary {
  opsBrief?: { cadence?: string; deliveryTime?: string; nextIso?: string };
}

export function OpsBriefCard() {
  const [next, setNext] = useState<Date | undefined>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | undefined>();

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        const result = await api.clientPortalSummary<Summary>();
        if (cancelled) return;
        if (result.opsBrief?.nextIso) setNext(new Date(result.opsBrief.nextIso));
      } catch (err) {
        if (!cancelled) setError(err instanceof ApiError ? err.message : "");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    void load();
    return () => { cancelled = true; };
  }, []);

  const daysUntil = next ? Math.max(0, Math.round((next.getTime() - Date.now()) / (1000 * 60 * 60 * 24))) : undefined;

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
      <div className="flex items-center gap-2 mb-2">
        <FileText size={14} className="text-slate-700" />
        <p className="text-xs font-mono uppercase tracking-wide text-slate-500">Weekly ops brief</p>
      </div>
      {loading ? (
        <div className="flex items-center gap-2 text-xs text-slate-500"><Loader2 size={12} className="animate-spin" /> Loading…</div>
      ) : error ? (
        <p className="text-xs text-slate-500">On schedule</p>
      ) : (
        <>
          <p className="text-lg font-semibold text-slate-900 leading-tight">
            {daysUntil === 0 ? "Landing today" : daysUntil === 1 ? "Landing tomorrow" : `In ${daysUntil ?? "—"} days`}
          </p>
          <p className="mt-1 flex items-center gap-1 text-[11px] text-slate-500">
            <Calendar size={11} />
            {next ? `${next.toLocaleDateString(undefined, { weekday: "long" })} 07:00 PT` : "Weekly · Mon 07:00 PT"}
          </p>
        </>
      )}
    </div>
  );
}
